/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java_MysqlConn;


import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;


/**
 *
 * @author matheus braum
 */
public class Java_MysqlConn extends javax.swing.JFrame {
    //acesso ao DB
    private static final String username = "root"; //seu username DB
    private static final String password = "123"; //sua senha DB
    private static final String dataConn = "jdbc:mysql://localhost:3306/connector"; //nome do seu bd/schema
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    
    public Java_MysqlConn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void upDateDB() //Credits for Oamen
    {
        try
        {
           
           Class.forName("com.mysql.cj.jdbc.Driver"); 
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("select * from connector");
            
            rs =pst.executeQuery();
            ResultSetMetaData StData = rs.getMetaData();
            
            q = StData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                
                Vector columnData = new Vector();
                
                for (i = 1; i <= q; i++)
                {
                   columnData.add(rs.getString("id"));
                   columnData.add(rs.getString("Nome"));
                   columnData.add(rs.getString("Telefone"));
                   columnData.add(rs.getString("Endereço"));
                   columnData.add(rs.getString("QtdCascos"));
                   columnData.add(rs.getString("Marca"));
                   columnData.add(rs.getString("Data"));
                }
                RecordTable.addRow(columnData);                
                
            }
         
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
        
    }
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtEndereço = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtData = new javax.swing.JTextField();
        jtxtMarca = new javax.swing.JTextField();
        jtxtQtdCascos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jbtnSair = new javax.swing.JButton();
        jbtnAdicionar = new javax.swing.JButton();
        jbtnIniciarBD = new javax.swing.JButton();
        jbtnAtualizar = new javax.swing.JButton();
        jbtnImprimir = new javax.swing.JButton();
        jbtnLimpar = new javax.swing.JButton();
        jbtnExcluir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasa do Doce (beta)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setText("Nome");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jtxtNome.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel2.add(jtxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 570, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setText("Telefone");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jtxtTelefone.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel2.add(jtxtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 570, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setText("Endereço");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jtxtEndereço.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel2.add(jtxtEndereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 570, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setText("Data");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jtxtData.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel2.add(jtxtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 570, -1));

        jtxtMarca.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel2.add(jtxtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 570, -1));

        jtxtQtdCascos.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel2.add(jtxtQtdCascos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 570, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setText("Marca");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setText("Qtd Cascos");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "Endereço", "QtdCascos", "Marca", "Data"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 740, 380));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 740, 640));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnSair.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 190, 50));

        jbtnAdicionar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnAdicionar.setText("Adicionar");
        jbtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdicionarActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 50));

        jbtnIniciarBD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnIniciarBD.setText("Iniciar BD");
        jbtnIniciarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIniciarBDActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnIniciarBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 50));

        jbtnAtualizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnAtualizar.setText("Atualizar");
        jbtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAtualizarActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 50));

        jbtnImprimir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnImprimir.setText("Imprimir");
        jbtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImprimirActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, 50));

        jbtnLimpar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnLimpar.setText("Limpar");
        jbtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, 50));

        jbtnExcluir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExcluir.setText("Excluir");
        jbtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 230, 640));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Kasa do Doce (beta)");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirme se deseja sair","MySQL Connector",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnSairActionPerformed

    private void jbtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparActionPerformed
        jtxtNome.setText(""); //limpa textfield
        jtxtTelefone.setText("");
        jtxtEndereço.setText("");
        jtxtQtdCascos.setText("");
        jtxtMarca.setText("");
        jtxtData.setText("");
    }//GEN-LAST:event_jbtnLimparActionPerformed

    private void jbtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdicionarActionPerformed
        try
        {
           
           Class.forName("com.mysql.cj.jdbc.Driver"); 
            sqlConn = DriverManager.getConnection(dataConn,username,password);           
             pst = sqlConn.prepareStatement("insert into connector(Nome,Telefone,Endereço,QtdCascos,"
                    + "Marca,Data)value(?,?,?,?,?,?)");
            
            pst.setString(1, jtxtNome.getText());
            pst.setString(2, jtxtTelefone.getText());
            pst.setString(3, jtxtEndereço.getText());
            pst.setString(4, jtxtQtdCascos.getText());
            pst.setString(5, jtxtMarca.getText());
            pst.setString(6, jtxtData.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Registro adicionado com sucesso");
            upDateDB();
        }
        
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, 
                    null, ex);
        } catch (SQLException ex) {
             //System.err.println(ex);
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } 
    }//GEN-LAST:event_jbtnAdicionarActionPerformed

    private void jbtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAtualizarActionPerformed
        try
        {
           
           Class.forName("com.mysql.cj.jdbc.Driver"); 
            sqlConn = DriverManager.getConnection(dataConn,username,password);           
             pst = sqlConn.prepareStatement("insert into connector(Nome,Telefone,Endereço,QtdCascos,"
                    + "Marca,Data)value(?,?,?,?,?,?)");
            
            pst.setString(1, jtxtNome.getText());
            pst.setString(2, jtxtTelefone.getText());
            pst.setString(3, jtxtEndereço.getText());
            pst.setString(4, jtxtQtdCascos.getText());
            pst.setString(5, jtxtMarca.getText());
            pst.setString(6, jtxtData.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Novos dados adicionados/atualizados\n\nAVISO: Exclua os dados antigos para"
                    + " maior controle\n\n\nOBS: Utilize o ID para localizar os dados antigos com maior facilidade");
            upDateDB();
        }
        
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, 
                    null, ex);
        } catch (SQLException ex) {
             //System.err.println(ex);
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } 
    }//GEN-LAST:event_jbtnAtualizarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        jtxtNome.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        jtxtTelefone.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        jtxtEndereço.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        jtxtQtdCascos.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        jtxtMarca.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        jtxtData.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnIniciarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIniciarBDActionPerformed
        try
        {
           
           Class.forName("com.mysql.cj.jdbc.Driver"); 
            sqlConn = DriverManager.getConnection(dataConn,username,password);           
             pst = sqlConn.prepareStatement("update connector set Nome =?, Telefone = ?,"
                     + "Endereço =?, QtdCascos =?, Marca =? where id =?");
            
            pst.setString(1, jtxtNome.getText());
            pst.setString(2, jtxtTelefone.getText());
            pst.setString(3, jtxtEndereço.getText());
            pst.setString(4, jtxtQtdCascos.getText());
            pst.setString(5, jtxtMarca.getText());
            pst.setString(6, jtxtData.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Banco de Dados Inicializado com sucesso");
            upDateDB();
        }
        
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, 
                    null, ex);
        } catch (SQLException ex) {
             //System.err.println(ex);
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } 
    }//GEN-LAST:event_jbtnIniciarBDActionPerformed

    private void jbtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImprimirActionPerformed
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnImprimirActionPerformed

    private void jbtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcluirActionPerformed
                DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try
        {
                    id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
                  
                   deleteItem = JOptionPane.showConfirmDialog(null,"Confirme se deseja excluir os dados selecionados",
                   "Aviso",JOptionPane.YES_NO_OPTION);
             if (deleteItem ==JOptionPane.YES_OPTION ) 
             {                 
         
           Class.forName("com.mysql.cj.jdbc.Driver"); 
            sqlConn = DriverManager.getConnection(dataConn,username,password);
                pst = sqlConn.prepareStatement("delete from connector where id =?");
                
               pst.setInt(1, id);
               pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Dados atualizados");
            upDateDB();
            
            jtxtNome.setText("");
            jtxtNome.requestFocus();
            jtxtTelefone.setText("");
            jtxtEndereço.setText("");
            jtxtQtdCascos.setText("");
            jtxtMarca.setText("");
            jtxtData.setText("");
            
             }
           
        }
        
        catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, 
           null, ex);
        } catch (SQLException ex) {
             System.err.println(ex);

        }      
    
    }//GEN-LAST:event_jbtnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Java_MysqlConn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Java_MysqlConn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdicionar;
    private javax.swing.JButton jbtnAtualizar;
    private javax.swing.JButton jbtnExcluir;
    private javax.swing.JButton jbtnImprimir;
    private javax.swing.JButton jbtnIniciarBD;
    private javax.swing.JButton jbtnLimpar;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JTextField jtxtData;
    private javax.swing.JTextField jtxtEndereço;
    private javax.swing.JTextField jtxtMarca;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtQtdCascos;
    private javax.swing.JTextField jtxtTelefone;
    // End of variables declaration//GEN-END:variables
}
